site_name: morphine - derivatives from poppy
nav:
    - Home: index.md
    - 'New Features with Jax':
      - jit-compilation: notebooks/jit_demo.ipynb
theme:
  name: "material"
repo_url: https://github.com/benjaminpope/morphine
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates